#  Copyright (c) 2024, ezdxf contributors
#  License: MIT License
"""Resolve ACAD_PROXY_ENTITY objects into standard INSERT block references.

This module handles DWG files generated by applications like Autodesk Inventor
that store all drawing geometry inside proxy entities with references to block
definitions. The proxy entities have empty proxy graphics (no renderable data),
but their AcDbProxyEntity tags contain Code 340 handles pointing to
BLOCK_RECORD entities that hold the actual geometry.

Usage::

    import ezdxf
    from ezdxf.addons.proxy_resolve import resolve_proxy_entities

    doc = ezdxf.readfile("drawing.dxf")
    resolve_proxy_entities(doc)
    # doc now contains standard INSERT entities instead of proxy entities

The resolution rules are:

- **Paperspace proxy entities** (Code 330 handle is "0" or missing): the
  referenced block's entities are already in absolute paperspace coordinates,
  so the INSERT is placed at (0, 0, 0).

- **Modelspace proxy entities** (Code 330 handle points to a VIEWPORT): the
  block content needs to be placed at the viewport's ``view_center_point`` so
  the viewport correctly displays the geometry in paperspace.
"""
from __future__ import annotations
from typing import TYPE_CHECKING
import logging

import struct

if TYPE_CHECKING:
    from ezdxf.document import Drawing

logger = logging.getLogger("ezdxf")

__all__ = ["resolve_proxy_entities", "reconstruct_annotations"]


def get_entity_points(entity) -> list:
    t = entity.dxftype()
    pts = []
    if t == "LINE":
        pts.extend([entity.dxf.start, entity.dxf.end])
    elif t == "CIRCLE":
        pts.append(entity.dxf.center)
    elif t == "ARC":
        pts.append(entity.dxf.center)
    elif t == "LWPOLYLINE":
        for pt in entity.get_points():
            pts.append(pt)
    elif t == "MTEXT" or t == "TEXT":
        pts.append(entity.dxf.insert)
    elif t == "INSERT":
        pts.append(entity.dxf.insert)
    elif t == "SOLID" or t == "TRACE":
        for attr in ["vtx0", "vtx1", "vtx2", "vtx3"]:
            if entity.dxf.hasattr(attr):
                pts.append(entity.dxf.get(attr))
    return pts


def get_circles_recursive(block, doc, accum_offset=(0.0, 0.0, 0.0)) -> list:
    circles = []
    for entity in block:
        t = entity.dxftype()
        if t == "CIRCLE":
            circles.append((entity, accum_offset))
        elif t == "INSERT":
            nested_name = entity.dxf.name
            if nested_name in doc.blocks:
                nested_block = doc.blocks[nested_name]
                ins_pt = entity.dxf.insert
                new_offset = (accum_offset[0] + ins_pt.x, accum_offset[1] + ins_pt.y, accum_offset[2] + ins_pt.z)
                circles.extend(get_circles_recursive(nested_block, doc, new_offset))
    return circles


def get_block_geometry_bounds(block, doc, accum_offset=(0.0, 0.0, 0.0)) -> tuple[list[float], list[float]]:
    xs, ys = [], []
    for entity in block:
        t = entity.dxftype()
        if t == "ACAD_PROXY_ENTITY":
            continue
        elif t == "INSERT":
            nested_name = entity.dxf.name
            if nested_name in doc.blocks:
                nested_block = doc.blocks[nested_name]
                ins_pt = entity.dxf.insert
                new_offset = (accum_offset[0] + ins_pt.x, accum_offset[1] + ins_pt.y, accum_offset[2] + ins_pt.z)
                n_xs, n_ys = get_block_geometry_bounds(nested_block, doc, new_offset)
                xs.extend(n_xs)
                ys.extend(n_ys)
        else:
            pts = get_entity_points(entity)
            for pt in pts:
                xs.append(pt[0] + accum_offset[0])
                ys.append(pt[1] + accum_offset[1])
    return xs, ys


def reconstruct_annotations(doc: Drawing) -> None:
    """Decodes Tag 310 data of ACAD_PROXY_ENTITY centerline/center mark objects
    and reconstructs standard LINE geometries inside block definitions.
    """
    try:
        all_circle_ys = []
        for blk in doc.blocks:
            for entity, offset in get_circles_recursive(blk, doc):
                all_circle_ys.append(entity.dxf.center.y + offset[1])
        all_circle_ys = list(set(all_circle_ys))

        for block in doc.blocks:
            if block.name.startswith("*Paper_Space"):
                continue

            circles_with_offsets = get_circles_recursive(block, doc)
            xs, ys = get_block_geometry_bounds(block, doc)
            if not xs or not ys:
                continue

            xmin, xmax = min(xs), max(xs)
            ymin, ymax = min(ys), max(ys)
            x_center = (xmin + xmax) / 2.0
            y_center = (ymin + ymax) / 2.0
            width = xmax - xmin
            height = ymax - ymin

            proxies = [e for e in block if e.dxftype() == "ACAD_PROXY_ENTITY"]
            to_delete = []

            for entity in proxies:
                layer = entity.dxf.layer
                to_delete.append(entity)

                doubles = []
                acdb_tags = getattr(entity, "acdb_proxy_entity", None)
                if acdb_tags is not None:
                    for tag in acdb_tags:
                        if tag.code == 310:
                            data = tag.value
                            for offset in range(len(data) - 7):
                                chunk = data[offset : offset + 8]
                                val = struct.unpack("<d", chunk)[0]
                                if not (val != val) and abs(val) > 0.001 and abs(val) < 20000.0:
                                    doubles.append(val)
                unique_doubles = list(set(doubles))

                if "Mittelpunktmarkierung" in layer:
                    matched_circle = None
                    matched_offset = (0.0, 0.0, 0.0)
                    for circle, offset in circles_with_offsets:
                        cx = circle.dxf.center.x + offset[0]
                        cy = circle.dxf.center.y + offset[1]
                        x_match = any(abs(d - cx) < 0.1 for d in unique_doubles)
                        y_match = any(abs(d - cy) < 0.1 for d in unique_doubles)
                        if x_match and y_match:
                            matched_circle = circle
                            matched_offset = offset
                            break

                    if matched_circle:
                        cx = matched_circle.dxf.center.x + matched_offset[0]
                        cy = matched_circle.dxf.center.y + matched_offset[1]
                        r = matched_circle.dxf.radius
                        extend = 2.0
                        block.add_line((cx - r - extend, cy), (cx + r + extend, cy), dxfattribs={"layer": layer})
                        block.add_line((cx, cy - r - extend), (cx, cy + r + extend), dxfattribs={"layer": layer})

                elif "Mittellinie" in layer:
                    for d in unique_doubles:
                        if abs(d - (height / 2.0)) < 1.0:
                            extend = 10.0
                            block.add_line((x_center, ymin - extend), (x_center, ymax + extend), dxfattribs={"layer": layer})
                        elif abs(d - (width / 2.0)) < 1.0:
                            extend = 10.0
                            block.add_line((xmin - extend, y_center), (xmax + extend, y_center), dxfattribs={"layer": layer})
                        elif any(abs(abs(d) - abs(cy)) < 1.0 for cy in all_circle_ys):
                            extend = 5.25
                            block.add_line((xmin - extend, d), (xmax + extend, d), dxfattribs={"layer": layer})

            for entity in to_delete:
                try:
                    block.delete_entity(entity)
                except Exception:
                    pass
    except Exception as e:
        logger.error(f"Error during reconstruct_annotations: {e}")


def resolve_proxy_entities(doc: Drawing) -> int:
    """Resolve ACAD_PROXY_ENTITY objects into standard INSERT block references.

    Iterates over all layouts in the document, finds proxy entities with
    Code 340 references to BLOCK_RECORD entities, and replaces them with
    standard INSERT entities pointing to the same blocks.

    Args:
        doc: The DXF document to process.

    Returns:
        Number of proxy entities successfully resolved.

    """
    # First, reconstruct any centerline/center mark annotations in the block definitions
    reconstruct_annotations(doc)

    resolved_count = 0
    replacements: list[tuple] = []  # (layout, block_name, insert_point, dxfattribs)
    to_delete: list[tuple] = []  # (layout, entity)
    spaced_count = 0

    for layout in doc.layouts:
        for entity in list(layout):
            if entity.dxftype() != "ACAD_PROXY_ENTITY":
                continue

            # Check for empty/trivial proxy graphic (≤8 bytes = just header)
            proxy_graphic = entity.proxy_graphic
            if proxy_graphic is not None and len(proxy_graphic) > 8:
                continue  # has real proxy graphic, skip

            # Extract Code 340 (block handle) and Code 330 (viewport handle)
            block_handle = None
            viewport_handle = None

            acdb_tags = getattr(entity, "acdb_proxy_entity", None)
            if acdb_tags is None:
                continue

            for tag in acdb_tags:
                if tag.code == 340 and block_handle is None:
                    block_handle = tag.value
                elif tag.code == 330:
                    viewport_handle = tag.value

            if block_handle is None:
                continue

            # Resolve block handle to block name
            try:
                block_record = doc.entitydb.get(block_handle)
                if block_record is None or block_record.dxftype() != "BLOCK_RECORD":
                    continue
                block_name = block_record.dxf.get("name", None)
                if not block_name:
                    continue
            except Exception:
                continue

            # Determine insertion point based on layout type:
            # - Paperspace (viewport_handle is "0" or missing): insert at origin
            #   because block entities are already at absolute paperspace coords
            # - Modelspace (viewport_handle points to VIEWPORT): insert at the
            #   viewport's view_center_point so the viewport shows the content.
            #   We space multiple viewports far apart to isolate their views.
            insert_point = (0.0, 0.0, 0.0)
            if viewport_handle and viewport_handle != "0":
                try:
                    vp = doc.entitydb.get(viewport_handle)
                    if vp is not None and vp.dxftype() == "VIEWPORT":
                        # Space viewports far apart in model space to prevent overlaps/bleeding
                        unique_coord = (spaced_count * 2000.0, spaced_count * 2000.0, 0.0)
                        vp.dxf.view_center_point = (unique_coord[0], unique_coord[1])
                        insert_point = unique_coord
                        spaced_count += 1
                except Exception:
                    pass

            # Build INSERT attributes
            dxfattribs: dict = {}
            if entity.dxf.hasattr("layer"):
                dxfattribs["layer"] = entity.dxf.layer
            if entity.dxf.hasattr("color"):
                dxfattribs["color"] = entity.dxf.color

            replacements.append((layout, block_name, insert_point, dxfattribs))
            to_delete.append((layout, entity))
            logger.debug(
                "Resolved proxy entity %s to INSERT block '%s' at %s",
                entity.dxf.handle,
                block_name,
                insert_point,
            )

    # Phase 2: Add INSERT entities
    for layout, block_name, insert_point, dxfattribs in replacements:
        try:
            layout.add_blockref(block_name, insert_point, dxfattribs=dxfattribs)
            resolved_count += 1
        except Exception as e:
            logger.warning("Failed to add block reference '%s': %s", block_name, e)

    # Phase 3: Delete resolved proxy entities
    for layout, entity in to_delete:
        try:
            layout.delete_entity(entity)
        except Exception as e:
            logger.warning(
                "Failed to delete proxy entity %s: %s", entity.dxf.handle, e
            )

    if resolved_count > 0:
        logger.info(
            "Resolved %d proxy entities into INSERT block references",
            resolved_count,
        )

    return resolved_count
